### ISSUE TITLE
[FEATURE] ExtraSign Improvements

### ISSUE THREAD

**Issue by wce2005a** [RusherDevelopment/rusherhack-issues#1147] opened 2021-11-30 23:56 UTC
**What feature would you like to be added.**
Instead of presets of sign dates, EU/US, make it so we can customize the dates so
*signdate %date%, %time% / %ign%
/ for new line
or an alternative verbose, %mon% %day% %year% %24htime% %time% / %currentalias%

**Is your feature request related to a problem? Please describe.**
US/EU Times are mixed, this makes it more clear.

**Additional context**
n/a

**Comment by jumboman32** [comment] 2021-12-01 23:01
add a title next time pls

**Comment by wce2005a** [comment] 2021-12-02 05:46
> 

Oops sorry

**Comment by FluorideHistorian** [comment] 2023-09-12 19:18
duplicate of #819

**Closed by FluorideHistorian** 2023-09-12 19:18 UTC
Labels: enhancement, module-enhancement
