### ISSUE TITLE
[FEATURE] Auto Completations on Chat / Console

### ISSUE THREAD

**Issue by synnkfps** [RusherDevelopment/rusherhack-issues#1328] opened 2022-07-24 02:01 UTC
**What feature would you like to be added.**
When pressing `*` on chat or just pressing the text field on console, pop up a kind of a ComboBox, with all the possible completations of what you have typed (show all the possible ones if its blank), it's like the Minecraft 1.14+ chat feature...
 
Also it could allow you to press `up` or `down` arrow keys to switch between auto completations. (sorry I don't know if that word exists)

**Is your feature request related to a problem? Please describe.**
Because when I'm typing some command, I need to type it correctly, and there are chances of what I'm typing do not exists, so with that feature, it will show me the suggestions of what I'm typing.

**Additional context**
And also, it could accept the current module settings, example:

```txt
                   +--------+
                   | scale  |
                   | key    |
                   |        |
*clickgui <dark gray first suggestion>
```
then it could show what are the type of the current selected auto completion, `boolean`, `int`

poor example:
![image](https://user-images.githubusercontent.com/93355393/180629078-416db29c-68fa-430b-8ec2-4cd005c1c674.png)

**Comment by TwoThreeTwo** [comment] 2022-07-24 02:08
john.

**Comment by synnkfps** [comment] 2022-07-24 02:10
![image](https://user-images.githubusercontent.com/93355393/180629248-b7f0d1d4-7463-48a1-b615-a632d6ca4744.png)

another example of it indicating int, i forgot to add

**Comment by Ozynt** [comment] 2022-08-01 23:21
Thank you for your suggestion but this has already been suggested and is planned to be added. Duplicate of #66

**Comment by FluorideHistorian** [comment] 2023-09-12 20:05
this was added in v2.0

**Closed by FluorideHistorian** 2023-09-12 20:05 UTC
Labels: enhancement
