### ISSUE TITLE
[FEATURE] ScreenshotProtect

### ISSUE THREAD

**Issue by Coop3r** [RusherDevelopment/rusherhack-issues#1248] opened 2022-03-04 14:00 UTC
ScreenshotProtect Module, when toggled on, and you take a screenshot rusherhack coordinates and direction are removed from the screenshot or blurred.

**Comment by quackitiy** [comment] 2022-03-13 22:10
hey coopurr, just disable coords before taking screenie :)

**Comment by Doogie13** [comment] 2022-03-25 15:37
> hey coopurr, just disable coords before taking screenie :)

effort

**Comment by FluorideHistorian** [comment] 2023-09-11 23:29
duplicate of #378

**Closed by FluorideHistorian** 2023-09-11 23:29 UTC
Labels: enhancement
