### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Neria44** [RusherDevelopment/rusherhack-issues#1399] opened 2022-12-01 02:06 UTC
**What feature would you like to be added.**
I would like to add chunk comparison that tells what blocks have been added/removed in a list.

**Is your feature request related to a problem? Please describe.**
Its just a suggest its not related to any other problem.

**Additional context**
to add a change seed option to it.

**Comment by FlowingMercury** [comment] 2022-12-11 01:22
> This would require effectively downloading every chunk you visit.

If i'm guessing correctly, you could just save chunks to memory and generate some sort of hash from that data and compare it to what it's supposed to be and see if it's different. 

Very basic way of doing it and you wouldn't be able to see which blocks were changed but it probably wouldn't be too hard to implement. 

I am not a programmer though so apologies if i sound stupid.

**Comment by Mathrandom7910** [comment] 2022-12-11 05:48
that would work, but what neria44 wanted was a way to list every block that changed. A hash is a one-way conversion, and there is no way of getting the chunk data back without brute forcing it.

**Comment by CoC-Fire** [comment] 2022-12-11 08:55
I'm assuming you would want this to determine if someone has been at your base.
This could be implemented by initially creating a world download of that area and saving it to a specific folder, then when you want to compare it, you create another world download of the area, enable an esp for changed blocks, for example, green if a block was added, red a block was removed or changed, and yellow if a block was removed and something else was put in its place.

**Comment by John200410** [comment] 2023-02-14 20:48
Duplicate of #298

**Closed by John200410** 2023-02-14 20:48 UTC
Labels: enhancement
