### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by LineZer0z** [RusherDevelopment/rusherhack-issues#1491] opened 2023-09-06 01:47 UTC
**autobed.**
auto crystal but for beds 

**Additional context**
if a bed is in your inventory place and use the bed there could be 2 modes nether mode and overworld mode nether mode would be like auto crystal and overworld mode would wait for night and then sleep in the bed i can provide some code if that helps majora1212 on discord

**Comment by FluorideHistorian** [comment] 2023-09-06 01:49
duplicate of #8

**Closed by FluorideHistorian** 2023-09-06 01:49 UTC
Labels: enhancement
