### ISSUE TITLE
[FEATURE] elytra sounds setting in elytra fly

### ISSUE THREAD

**Issue by GentlemanMC** [RusherDevelopment/rusherhack-issues#1481] opened 2023-08-31 12:12 UTC
**What feature would you like to be added.**
a setting to turn on/off the elytraflying sounds (they are so loud)
**Is your feature request related to a problem? Please describe.**
i hate the sound *WOOOOOOSHHHHHHHHHHHHHHHHHHHHHHHHHHHH*

**Comment by Toska2b2t** [comment] 2023-09-01 20:34
You can also edit the sounds in your minecraft settings for now

**Comment by FluorideHistorian** [comment] 2023-09-12 20:35
duplicate of #1079

**Closed by FluorideHistorian** 2023-09-12 20:35 UTC
Labels: enhancement
