### ISSUE TITLE
[FEATURE] AutoObsidian

### ISSUE THREAD

**Issue by Zamplex** [RusherDevelopment/rusherhack-issues#1443] opened 2023-04-09 18:41 UTC
**What feature would you like to be added.**
AutoObsidian. Automatically mine echests for obsidian, would be a faser way of obtaining obsidian than mining manually.

**Is your feature request related to a problem? Please describe.**
None

**Additional context**
None

**Comment by FluorideHistorian** [comment] 2023-04-09 20:24
nuker + scaffold

**Comment by FluorideHistorian** [comment] 2023-04-09 20:25
also duplicate of a few issues

**Closed by FluorideHistorian** 2023-04-09 20:25 UTC
Labels: enhancement
