### ISSUE TITLE
[FEATURE] Crystal Base Place

### ISSUE THREAD

**Issue by Projekt8276** [RusherDevelopment/rusherhack-issues#1493] opened 2023-09-10 22:56 UTC
Crystal Base place would be an addon to crystal aura, and It would place obsidian in order to hit enemies with crystals in locations that are not usually suitable for CPVP, such as above ground on grass

**Comment by FluorideHistorian** [comment] 2023-09-10 22:59
duplicate of #628

**Closed by FluorideHistorian** 2023-09-10 22:59 UTC
Labels: enhancement
