### ISSUE TITLE
[FEATURE] More ExtraSign module DateAppend settings

### ISSUE THREAD

**Issue by Toska2b2t** [RusherDevelopment/rusherhack-issues#1483] opened 2023-09-01 20:55 UTC
Currently there are two settings for date formatting to add to signs, EU and US but this can get confusing, 01-09-2023 could mean either january first or first of september. Adding an option for the shortened month name to be used instead of it's number would be based; 01-09-2023 could become 1-Sep-2023 using this setting. Ability to enable ordinal suffixes (1st, 2nd, 3rd) very cool too so you could have it write Sep-1st-2023 for example.

Another thing that would be very nice, the ability to change the dash separator to a slash, space or any other chosen character.

**Comment by FluorideHistorian** [comment] 2023-09-12 20:36
duplicate of #819

**Closed by FluorideHistorian** 2023-09-12 20:36 UTC
Labels: enhancement
