### ISSUE TITLE
[FEATURE] Search Packet in AntiPacket / PacketLog

### ISSUE THREAD

**Issue by synnkfps** [RusherDevelopment/rusherhack-issues#1327] opened 2022-07-23 15:42 UTC
**What feature would you like to be added.**
Just a text field that will real-time search the text you put in, so you can find packets easier with it.

**Is your feature request related to a problem? Please describe.**
Because sometimes when I need to find some packet, I take some time to find it, with the feature it won't happen.

**Additional context**
It could be like: a text field, that when you put any letters there it will in-real-time search, and a locate button on the side of it, which when you click it, it will highlight the packet/whatever you put. And it could have a Ctrl+A / Up-down arrows to switch between the history of searches, the Ctrl+A is just to select all

**Comment by FluorideHistorian** [comment] 2023-09-11 23:27
duplicate of #795

**Closed by FluorideHistorian** 2023-09-11 23:27 UTC
Labels: enhancement, module-enhancement
