### ISSUE TITLE
[FEATURE] AutoBreak EnderChest (Module Meteor)

### ISSUE THREAD

**Issue by bastianmarin** [RusherDevelopment/rusherhack-issues#1614] opened 2024-04-29 23:50 UTC
**What feature would you like to be added.**
In short, it farms the enderchest in your inventory, it works with packetbreak and is very fast.

**Is your feature request related to a problem? Please describe.**
Nothing

**Additional context**
Nothing

![imagen](https://github.com/RusherDevelopment/rusherhack-issues/assets/55340002/889e3f10-cd73-4fd6-a930-fe0592017954)

**Comment by FluorideHistorian** [comment] 2024-04-29 23:52
scaffold + fastbreak autoremine and also duplicate of #1433

**Closed by FluorideHistorian** 2024-04-29 23:52 UTC
Labels: enhancement
