### ISSUE TITLE
Viewmodel Shader [BUG] 

### ISSUE THREAD

**Issue by goldendrip** [RusherDevelopment/rusherhack-issues#1560] opened 2024-01-20 20:41 UTC
Shader in viewmodel renders at a diffrent position than the actual viewmodel.
![image](https://github.com/RusherDevelopment/rusherhack-issues/assets/81508141/6b735abd-f0e9-4338-a894-13aaf1377cd2)

**Comment by Badinek** [comment] 2024-01-20 20:43
Known issue caused by incompatibility with future client.

**Comment by FluorideHistorian** [comment] 2024-08-01 01:46
closing in favor of #1692

**Closed by FluorideHistorian** 2024-08-01 01:46 UTC
Labels: bug
