### ISSUE TITLE
[FEATURE] Map downloader

### ISSUE THREAD

**Issue by CozyMeli-gitv2** [RusherDevelopment/rusherhack-issues#1385] opened 2022-10-15 22:30 UTC
**What feature would you like to be added.**
A module that downloads all maps that enter your render distance, or inventory, to a folder in your .minecraft. This would make archiving maps you ever see easy, and convenient. No more screenshoting cool ass maps you see, because they would get saved instantly to a folder. 

This module shouldn't have any performance hit, due to a single map being under a megabyte. Also due to a shitton of maps sometimes at spawn, I advise using a thread that is off main, because lag isn't nice.

**Is your feature request related to a problem? Please describe.**
Nope! Just a feature request.

**Additional context**
Lambda Client has this feature, and I would love seeing it on rusherhack. As I said in my last issue, the day I can stop using multiple mods alongside rusher, is the day I can die happy.

**Comment by FluorideHistorian** [comment] 2023-09-11 23:26
duplicate of #1113

**Closed by FluorideHistorian** 2023-09-11 23:26 UTC
Labels: enhancement
