### ISSUE TITLE
[FEATURE] Nametags size suggestion

### ISSUE THREAD

**Issue by gggghuuh** [RusherDevelopment/rusherhack-issues#1770] opened 2024-10-15 15:28 UTC
pls get nametags to work better with zoom module. when zoom is used, the nametags get funky and small (doesn't look right)
![2024-10-16_02 23 23](https://github.com/user-attachments/assets/c6aa6e6a-8ee7-4fba-bd7b-d4278b57a030)
![2024-10-16_02 23 38](https://github.com/user-attachments/assets/3a6ffd11-32fe-4832-b321-eeaa82f5319f)

**Comment by John200410** [comment] 2024-10-15 22:35
duplicate of #1626

**Closed by John200410** 2024-10-15 22:35 UTC
Labels: enhancement
