### ISSUE TITLE
[FEATURE] arraylist improvements

### ISSUE THREAD

**Issue by SoggyBacco** [RusherDevelopment/rusherhack-issues#955] opened 2021-07-22 06:33 UTC
more customization options such as alphabetical ordering and color coding

maybe metadata for more modules too
ex: AutoCrystal [dmg]

**Comment by tycrek** [comment] 2021-07-25 17:51
I'd also like to customize which modules show metadata, and for some customize what data is being shown

**Comment by FluorideHistorian** [comment] 2023-09-12 17:36
alphabetical ordering is possible
color coding duplicate of #1183 
autocrystal now has damage metadata option

**Closed by FluorideHistorian** 2023-09-12 17:36 UTC
Labels: enhancement
