### ISSUE TITLE
[FEATURE] Baritone Travel Option for Base Finder

### ISSUE THREAD

**Issue by Alexsen56** [RusherDevelopment/rusherhack-issues#1406] opened 2022-12-22 12:05 UTC
Add an option to use Baritone as the travel method for the Base Finder module. It could use the ".thisway" command and rotate every so often just like the elytra fly method does.

**Comment by CoC-Fire** [comment] 2022-12-24 09:21
just use #explore

**Comment by FluorideHistorian** [comment] 2023-09-12 19:49
duplicate of #892

**Closed by FluorideHistorian** 2023-09-12 19:49 UTC
Labels: module-enhancement
