### ISSUE TITLE
[FEATURE]custom shader command for shaderESP

### ISSUE THREAD

**Issue by GentlemanMC** [RusherDevelopment/rusherhack-issues#1140] opened 2021-11-24 13:51 UTC
**What feature would you like to be added.**
an option to load custom shaders to shaderESP

**Additional context**
this is an example of it 
https://streamable.com/wm5vog

**Comment by LiquidSmokeBalls** [comment] 2021-11-26 05:00
I think john might have said he will do it soon but most likely not (Then again I do not know, so I could be wrong about that)

**Comment by GentlemanMC** [comment] 2021-11-26 08:51
> I think john might have said he will do it soon but most likely not (Then again I do not know, so I could be wrong about that)

he will do it soon
exactly like he did to the targetHUD and the bedAura :trollface:

**Comment by FluorideHistorian** [comment] 2023-09-12 19:15
duplicate of #927

**Closed by FluorideHistorian** 2023-09-12 19:15 UTC
Labels: enhancement
