### ISSUE TITLE
[FEATURE] Preset for specific modules that are changable

### ISSUE THREAD

**Issue by wce2005a** [RusherDevelopment/rusherhack-issues#1164] opened 2021-12-18 16:48 UTC
**What feature would you like to be added.**
I would like a way (like Future has) to use *preset or *config, for a specific module, I change a lot of settings so I can't have 2 completely different profiles, For example: I want a way to switch between fireworks elytra mode for 2b and the boost mode, and there are different settings you have to change for each

**Is your feature request related to a problem? Please describe.**
If you're afk or just traveling in the overworld generally, I don't wanna just be using fireworks 24/7 (bleh yes im poor on 2b) so I would like a way to switch if I need to

**Additional context**

**Comment by John200410** [comment] 2024-01-31 22:38
Duplicate of #242

**Closed by John200410** 2024-01-31 22:38 UTC
Labels: enhancement
