### ISSUE TITLE
Config auto load

### ISSUE THREAD

**Issue by LogicalArithmetic** [RusherDevelopment/rusherhack-issues#1551] opened 2024-01-17 21:01 UTC
Configs automatically load when joining a specific server based on the servers IP.

Meteor Client has this feature when saving configs.

**Comment by Taylhurx** [comment] 2024-01-18 23:44
I think this would be a good thing to add but it might be some work

**Comment by FluorideHistorian** [comment] 2024-07-23 14:12
duplicate of #227

**Closed by FluorideHistorian** 2024-07-23 14:12 UTC
