### ISSUE TITLE
[BUG]  please consider fixing jesus strict on constantiam

### ISSUE THREAD

**Issue by LineZer0z** [RusherDevelopment/rusherhack-issues#1594] opened 2024-03-12 21:31 UTC
**Describe the bug**
jesus strict has many issues ranging from weird movement stuttering and sometimes not work at all on constantiam

**To Reproduce**
hop on constantiam and use jesus strict

**Other mods**
n/a

**Expected behavior**
strict should work as intended

**Additional context**
as a side note i would use future's jesus strict but rusher breaks it

**Comment by FluorideHistorian** [comment] 2024-04-18 23:29
duplicate of #1585

**Closed by FluorideHistorian** 2024-04-18 23:29 UTC
Labels: bug
