### ISSUE TITLE
[FEATURE] Flat Sand Phase 

### ISSUE THREAD

**Issue by bstar16** [RusherDevelopment/rusherhack-issues#975] opened 2021-07-27 02:38 UTC
Sand phase except it doesn’t go through the floor, can be used where boatfly is patched for boat phase pretty sure forgehax and cool k have this.
Edit: you basically would stay on the same y level as the block you placed your boat on

**Comment by FluorideHistorian** [comment] 2023-09-11 22:38
duplicate of #537 which is resolved

**Closed by FluorideHistorian** 2023-09-11 22:38 UTC
Labels: enhancement
