### ISSUE TITLE
[FEATURE]  whisper history

### ISSUE THREAD

**Issue by 06d** [RusherDevelopment/rusherhack-issues#1329] opened 2022-07-26 17:53 UTC
a command that if typed, just shows you all of the past, (for example) 30 whispers you've had on a server

if i go afk, and i come back i want to know if someone msgd me or something, or someone says something autistic and i just forgot to screenshot

it would go really well with the console imo

**Comment by FluorideHistorian** [comment] 2023-09-12 14:27
sort of a duplicate of #185

**Closed by FluorideHistorian** 2023-09-12 14:27 UTC
Labels: enhancement
